server:
  port: 8081
build:
  version: "${project.version}"
spring:
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate.ddl-auto: "none"
    show-sql: true
  datasource:
    url: "jdbc:h2:file:~/h2/users"
    username: "sa"
    password: null
    driverClassName: "org.h2.Driver"
  h2:
    console:
      enabled: true
      path: "/h2-console"
  flyway:
    enabled: true
    validate-on-migrate: true
  data:
    web:
      pageable:
        default-page-size: 100
        max-page-size: 200
springdoc:
  api-docs:
    path: "/api-docs"
    version: "openapi-3-1"
  default-produces-media-type: "application/json"
  auto-tag-classes: false
  override-with-generic-response: false

application:
  minimal-age-in-years: 18
  user-sort-by: birthdate
  user-sort-direction: DESC


