server:
  port: 8081
spring:
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate.ddl-auto: "none"
    show-sql: true
  datasource:
    url: "jdbc:h2:file:~/users"
    username: "sa"
    password: null
    driverClassName: "org.h2.Driver"
  h2:
    console:
      enabled: true
      path: "/h2-console"
  flyway:
    enabled: true
    validate-on-migrate: true
